### ISSUE TITLE
Ryan's TODO List

### ISSUE THREAD

**Issue by ryanwarsaw** [theirc/coach-erevu#82]
### TODO

- [x] Add header bar to the topic selection menu (Needs discussion)
- [x] Fix the home screen layout to be a 40/60 ratio, fix padding on the image.
- [x] Don't open a topic selection menu if there is only one topic, just go directly to that topic.
- [x] Fix some funky layout stuff with the action activity on small devices.
- [x] Investigate into the question text not wrapping on the quiz menu (Trying to replicate)

**Comment by lauradereynal** [comment]
Hi Ryan, how are these going ?

**Comment by ryanwarsaw** [comment]
@lauradereynal All of these are happening in the same patch, due to the fact they're all related to the layout of the app. I've got some pending changes I discussed with @secretrobotron last Sunday, I haven't had sufficient time to get that PR ready just yet - expect an update over the weekend (looking to hopefully land it in production)
